kind = "mobile"
previewPath = "/rummy-app-mobile/"
title = "RummyApp Mobile"
version = "1.0.0"
id = "artifacts/rummy-app-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/rummy-app-mobile/" ]
localPort = 22604

[services.development]
run = "pnpm --filter @workspace/rummy-app-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rummy-app-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rummy-app-mobile", "run", "serve" ]

[services.env]
PORT = "22604"
BASE_PATH = "/rummy-app-mobile/"
